local Skills = {
	[301] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 30,
			name = "神龙摆尾",
			description = "攻击前两排",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 5,
			name = "亢龙有悔",
			description = "短时间内提升自己的伤害",
			kind = "passive",
			rate = 0.5,
			duration = 1000,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 100,
			name = "飞龙在天",
			description = "攻击对方全体成员",
			kind = "attackForAll",
			rate = 5,
			duration = 1,
		},
	},
	[302] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 15,
			name = "贵妃醉酒",
			description = "对对方前排一名成员造成部分伤害，并短时眩晕对方",
			kind = "attackFrontForAll",
			rate = 3,
			duration = 5,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 5,
			name = "金钟罩",
			description = "大幅提升自己的防御，有时间限制",
			kind = "attackFrontForAll",
			rate = 0.5,
			duration = 5,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 100,
			name = "如来神掌",
			description = "对沿途的敌人造成大量伤害，最多命中三个敌人",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
	},
	[303] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 40,
			name = "一苇渡江",
			description = "对一名中排敌人造成中等伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 40,
			name = "拈花指",
			description = "对前排敌人造成伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 50,
			name = "一阳指",
			description = "对后排敌人造成伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
	},
	[305] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 15,
			name = "托塔伏妖",
			description = "对一名中排敌人造成中等伤害",
			kind = "attackFrontForAll",
			rate = 3,
			duration = 1,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 100,
			name = "诛仙阵",
			description = "对前排敌人造成伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 25,
			name = "潇湘夜雨",
			description = "对后排敌人造成伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
	},
	[308] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 50,
			name = "血战八方",
			description = "对前排所有敌人造成大范围伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 10,
			name = "神龙附体",
			description = "增加友方所有成员的防御",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 5,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 100,
			name = "后发制人",
			description = "战斗最后对一名后排敌人造成大量伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
	},
	[312] = {
		["skill1"] = {
			icon = "iconpath",
			level = 1,
			attack = 80,
			name = "长生水",
			description = "对友方一名成员回复部分血量",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
		["skill2"] = {
			icon = "iconpath",
			level = 1,
			attack = 100,
			name = "坐地求全",
			description = "为自己加一个持续一定时间的护盾",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 5,
		},
		["skill3"] = {
			icon = "iconpath",
			level = 1,
			attack = 200,
			name = "无懈可击",
			description = "为任一队友抵消一次技能伤害",
			kind = "attackFrontForAll",
			rate = 5,
			duration = 1,
		},
	},
}